FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY ["StudentsApi.Api.csproj", "./"]

RUN dotnet restore "StudentsApi.Api.csproj"

COPY . .

RUN dotnet build "StudentsApi.Api.csproj" \
    -c Debug \
    -o /app/build


FROM mcr.microsoft.com/dotnet/sdk:8.0 AS final

WORKDIR /app

COPY --from=build /app/build .

ENV ASPNETCORE_ENVIRONMENT=Development
ENV ASPNETCORE_HTTP_PORTS=8080

EXPOSE 8080

ENTRYPOINT ["dotnet", "StudentsApi.Api.dll"]