services:
  mysql:
    image: mysql:8.0
    container_name: alunos-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: alunos-api
    restart: unless-stopped

    ports:
      - "8080:8080"

    env_file:
      - .env

    depends_on:
      - mysql

volumes:
  mysql_data: